services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - ..:/workspace:rw,Z
    environment:
      DOCKER_HOST: unix:///run/host-user-runtime/podman/podman.sock
    command: sleep infinity
